language: java
branches:
  only:
    - master
cache:
- echo "cache"

before_install:
- echo "before_install"

install:
- echo "install"

before_script:
- echo "before_script"

script:
- cd ./scripts
- sh ./package.sh

before_cache:
- echo "before_cache"

after_success:
- echo "after_success"

after_failure:
- echo "after_failure"

after_script:
- echo "after_script"
